### ISSUE TITLE
Bug applying migrations (fixtures)

### ISSUE THREAD

**Issue by donnerc** [shopozor/backend#68]
Here is the result of trying to install the fixtures data on a fresh install

```
[42703] FatalError: column "background_image_alt" of relation "product_categories" does not exist 
```
It appears that the data is not in sync with the database structure. This is precisely why I think we MUST keep the structure and the data in sync. An other way we may look at it is inspecting the database structure and generate the data based on the actual structure of the DB. We can't allow this kind of things to happen in production or in an urgent situation, for example trying to hotfix a bug in the production system.

**Comment by zadigus** [comment]
@donnerc I don't know with what commit number you are working, but if you base on the `dev` branch, that works perfectly. Indeed, the column you mention as missing is defined [here](https://github.com/shopozor/backend/blob/dev/database-service/migrations/1572625354176_adapt-to-fixtures/up.sql#L2).

**Comment by zadigus** [comment]
I will, however, cover the application of the fixtures' migrations with unit tests.

**Comment by donnerc** [comment]
as you can see the path to the file mentioned is https://github.com/shopozor/backend/blob/dev/database-service/migrations/1572625354176_adapt-to-fixtures/up.sql#L2 . That is, there is a `/` in the migration name which causes it not to be recognized as a migration to be applied. I don't think `hasura migrate apply` will watch recursively in subdirs.

**Comment by zadigus** [comment]
https://github.com/shopozor/backend/issues/74

**Comment by zadigus** [comment]
https://github.com/shopozor/backend/issues/69

**Comment by zadigus** [comment]
I've added the relevant tests.
