### ISSUE TITLE
Generate the `down` migration for the fixtures

### ISSUE THREAD

**Issue by donnerc** [shopozor/backend#69]
It could be a good thing to have both, the up and the down migration for the fixtures data. This should not be such big work. Just `DELETE FROM TABLE ...`

**Comment by zadigus** [comment]
Yeah I thought about it, but the principle of those fixtures is that they are injected into the database before the acceptance tests and after those tests the database is deleted. Therefore, I don't see the need for down migrations. I'll keep that in mind though, as I think it should be easy to do. It would also make the migrations more consistent.

**Comment by zadigus** [comment]
https://github.com/shopozor/backend/issues/74

**Comment by zadigus** [comment]
https://github.com/shopozor/backend/issues/68
